/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AccessTokenListResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccessTokenListResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccessTokenListResult
        //private AccessTokenListResult instance;

        public AccessTokenListResultTests()
        {
            // TODO uncomment below to create an instance of AccessTokenListResult
            //instance = new AccessTokenListResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccessTokenListResult
        /// </summary>
        [Fact]
        public void AccessTokenListResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccessTokenListResult
            //Assert.IsType<AccessTokenListResult>(instance);
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
