/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AlipayTradeRefundResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlipayTradeRefundResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlipayTradeRefundResponse
        //private AlipayTradeRefundResponse instance;

        public AlipayTradeRefundResponseTests()
        {
            // TODO uncomment below to create an instance of AlipayTradeRefundResponse
            //instance = new AlipayTradeRefundResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlipayTradeRefundResponse
        /// </summary>
        [Fact]
        public void AlipayTradeRefundResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AlipayTradeRefundResponse
            //Assert.IsType<AlipayTradeRefundResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Msg'
        /// </summary>
        [Fact]
        public void MsgTest()
        {
            // TODO unit test for the property 'Msg'
        }

        /// <summary>
        /// Test the property 'SubCode'
        /// </summary>
        [Fact]
        public void SubCodeTest()
        {
            // TODO unit test for the property 'SubCode'
        }

        /// <summary>
        /// Test the property 'SubMsg'
        /// </summary>
        [Fact]
        public void SubMsgTest()
        {
            // TODO unit test for the property 'SubMsg'
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

        /// <summary>
        /// Test the property 'IsError'
        /// </summary>
        [Fact]
        public void IsErrorTest()
        {
            // TODO unit test for the property 'IsError'
        }

        /// <summary>
        /// Test the property 'BuyerLogonId'
        /// </summary>
        [Fact]
        public void BuyerLogonIdTest()
        {
            // TODO unit test for the property 'BuyerLogonId'
        }

        /// <summary>
        /// Test the property 'BuyerOpenId'
        /// </summary>
        [Fact]
        public void BuyerOpenIdTest()
        {
            // TODO unit test for the property 'BuyerOpenId'
        }

        /// <summary>
        /// Test the property 'BuyerUserId'
        /// </summary>
        [Fact]
        public void BuyerUserIdTest()
        {
            // TODO unit test for the property 'BuyerUserId'
        }

        /// <summary>
        /// Test the property 'FundChange'
        /// </summary>
        [Fact]
        public void FundChangeTest()
        {
            // TODO unit test for the property 'FundChange'
        }

        /// <summary>
        /// Test the property 'GmtRefundPay'
        /// </summary>
        [Fact]
        public void GmtRefundPayTest()
        {
            // TODO unit test for the property 'GmtRefundPay'
        }

        /// <summary>
        /// Test the property 'HasDepositBack'
        /// </summary>
        [Fact]
        public void HasDepositBackTest()
        {
            // TODO unit test for the property 'HasDepositBack'
        }

        /// <summary>
        /// Test the property 'OpenId'
        /// </summary>
        [Fact]
        public void OpenIdTest()
        {
            // TODO unit test for the property 'OpenId'
        }

        /// <summary>
        /// Test the property 'OutTradeNo'
        /// </summary>
        [Fact]
        public void OutTradeNoTest()
        {
            // TODO unit test for the property 'OutTradeNo'
        }

        /// <summary>
        /// Test the property 'PreAuthCancelFee'
        /// </summary>
        [Fact]
        public void PreAuthCancelFeeTest()
        {
            // TODO unit test for the property 'PreAuthCancelFee'
        }

        /// <summary>
        /// Test the property 'PresentRefundBuyerAmount'
        /// </summary>
        [Fact]
        public void PresentRefundBuyerAmountTest()
        {
            // TODO unit test for the property 'PresentRefundBuyerAmount'
        }

        /// <summary>
        /// Test the property 'PresentRefundDiscountAmount'
        /// </summary>
        [Fact]
        public void PresentRefundDiscountAmountTest()
        {
            // TODO unit test for the property 'PresentRefundDiscountAmount'
        }

        /// <summary>
        /// Test the property 'PresentRefundMdiscountAmount'
        /// </summary>
        [Fact]
        public void PresentRefundMdiscountAmountTest()
        {
            // TODO unit test for the property 'PresentRefundMdiscountAmount'
        }

        /// <summary>
        /// Test the property 'RefundChargeAmount'
        /// </summary>
        [Fact]
        public void RefundChargeAmountTest()
        {
            // TODO unit test for the property 'RefundChargeAmount'
        }

        /// <summary>
        /// Test the property 'RefundChargeInfoList'
        /// </summary>
        [Fact]
        public void RefundChargeInfoListTest()
        {
            // TODO unit test for the property 'RefundChargeInfoList'
        }

        /// <summary>
        /// Test the property 'RefundCurrency'
        /// </summary>
        [Fact]
        public void RefundCurrencyTest()
        {
            // TODO unit test for the property 'RefundCurrency'
        }

        /// <summary>
        /// Test the property 'RefundDetailItemList'
        /// </summary>
        [Fact]
        public void RefundDetailItemListTest()
        {
            // TODO unit test for the property 'RefundDetailItemList'
        }

        /// <summary>
        /// Test the property 'RefundFee'
        /// </summary>
        [Fact]
        public void RefundFeeTest()
        {
            // TODO unit test for the property 'RefundFee'
        }

        /// <summary>
        /// Test the property 'RefundHybAmount'
        /// </summary>
        [Fact]
        public void RefundHybAmountTest()
        {
            // TODO unit test for the property 'RefundHybAmount'
        }

        /// <summary>
        /// Test the property 'RefundPresetPaytoolList'
        /// </summary>
        [Fact]
        public void RefundPresetPaytoolListTest()
        {
            // TODO unit test for the property 'RefundPresetPaytoolList'
        }

        /// <summary>
        /// Test the property 'RefundSettlementId'
        /// </summary>
        [Fact]
        public void RefundSettlementIdTest()
        {
            // TODO unit test for the property 'RefundSettlementId'
        }

        /// <summary>
        /// Test the property 'RefundVoucherDetailList'
        /// </summary>
        [Fact]
        public void RefundVoucherDetailListTest()
        {
            // TODO unit test for the property 'RefundVoucherDetailList'
        }

        /// <summary>
        /// Test the property 'SendBackFee'
        /// </summary>
        [Fact]
        public void SendBackFeeTest()
        {
            // TODO unit test for the property 'SendBackFee'
        }

        /// <summary>
        /// Test the property 'StoreName'
        /// </summary>
        [Fact]
        public void StoreNameTest()
        {
            // TODO unit test for the property 'StoreName'
        }

        /// <summary>
        /// Test the property 'TradeNo'
        /// </summary>
        [Fact]
        public void TradeNoTest()
        {
            // TODO unit test for the property 'TradeNo'
        }
    }
}
