/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AppPostResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppPostResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppPostResult
        //private AppPostResult instance;

        public AppPostResultTests()
        {
            // TODO uncomment below to create an instance of AppPostResult
            //instance = new AppPostResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppPostResult
        /// </summary>
        [Fact]
        public void AppPostResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppPostResult
            //Assert.IsType<AppPostResult>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ServerPath'
        /// </summary>
        [Fact]
        public void ServerPathTest()
        {
            // TODO unit test for the property 'ServerPath'
        }
    }
}
