/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AppSetting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppSettingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppSetting
        //private AppSetting instance;

        public AppSettingTests()
        {
            // TODO uncomment below to create an instance of AppSetting
            //instance = new AppSetting();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppSetting
        /// </summary>
        [Fact]
        public void AppSettingInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppSetting
            //Assert.IsType<AppSetting>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ProviderCode'
        /// </summary>
        [Fact]
        public void ProviderCodeTest()
        {
            // TODO unit test for the property 'ProviderCode'
        }

        /// <summary>
        /// Test the property 'GroupCode'
        /// </summary>
        [Fact]
        public void GroupCodeTest()
        {
            // TODO unit test for the property 'GroupCode'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'FrontendUsable'
        /// </summary>
        [Fact]
        public void FrontendUsableTest()
        {
            // TODO unit test for the property 'FrontendUsable'
        }

        /// <summary>
        /// Test the property 'CreateDate'
        /// </summary>
        [Fact]
        public void CreateDateTest()
        {
            // TODO unit test for the property 'CreateDate'
        }

        /// <summary>
        /// Test the property 'LastUpdate'
        /// </summary>
        [Fact]
        public void LastUpdateTest()
        {
            // TODO unit test for the property 'LastUpdate'
        }
    }
}
