/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AppSettingProviderPostResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppSettingProviderPostResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppSettingProviderPostResult
        //private AppSettingProviderPostResult instance;

        public AppSettingProviderPostResultTests()
        {
            // TODO uncomment below to create an instance of AppSettingProviderPostResult
            //instance = new AppSettingProviderPostResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppSettingProviderPostResult
        /// </summary>
        [Fact]
        public void AppSettingProviderPostResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppSettingProviderPostResult
            //Assert.IsType<AppSettingProviderPostResult>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
