/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateOrderResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateOrderResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateOrderResult
        //private CreateOrderResult instance;

        public CreateOrderResultTests()
        {
            // TODO uncomment below to create an instance of CreateOrderResult
            //instance = new CreateOrderResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateOrderResult
        /// </summary>
        [Fact]
        public void CreateOrderResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateOrderResult
            //Assert.IsType<CreateOrderResult>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'OrderNo'
        /// </summary>
        [Fact]
        public void OrderNoTest()
        {
            // TODO unit test for the property 'OrderNo'
        }
    }
}
