/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing HbFqPayInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HbFqPayInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HbFqPayInfo
        //private HbFqPayInfo instance;

        public HbFqPayInfoTests()
        {
            // TODO uncomment below to create an instance of HbFqPayInfo
            //instance = new HbFqPayInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HbFqPayInfo
        /// </summary>
        [Fact]
        public void HbFqPayInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" HbFqPayInfo
            //Assert.IsType<HbFqPayInfo>(instance);
        }

        /// <summary>
        /// Test the property 'FqAmount'
        /// </summary>
        [Fact]
        public void FqAmountTest()
        {
            // TODO unit test for the property 'FqAmount'
        }

        /// <summary>
        /// Test the property 'FqInstId'
        /// </summary>
        [Fact]
        public void FqInstIdTest()
        {
            // TODO unit test for the property 'FqInstId'
        }

        /// <summary>
        /// Test the property 'UserInstallNum'
        /// </summary>
        [Fact]
        public void UserInstallNumTest()
        {
            // TODO unit test for the property 'UserInstallNum'
        }
    }
}
