/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PhoneSignInRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhoneSignInRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhoneSignInRequest
        //private PhoneSignInRequest instance;

        public PhoneSignInRequestTests()
        {
            // TODO uncomment below to create an instance of PhoneSignInRequest
            //instance = new PhoneSignInRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhoneSignInRequest
        /// </summary>
        [Fact]
        public void PhoneSignInRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhoneSignInRequest
            //Assert.IsType<PhoneSignInRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'VerifyCode'
        /// </summary>
        [Fact]
        public void VerifyCodeTest()
        {
            // TODO unit test for the property 'VerifyCode'
        }

        /// <summary>
        /// Test the property 'TwoFactorCode'
        /// </summary>
        [Fact]
        public void TwoFactorCodeTest()
        {
            // TODO unit test for the property 'TwoFactorCode'
        }
    }
}
