/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PresetPayToolInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PresetPayToolInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PresetPayToolInfo
        //private PresetPayToolInfo instance;

        public PresetPayToolInfoTests()
        {
            // TODO uncomment below to create an instance of PresetPayToolInfo
            //instance = new PresetPayToolInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PresetPayToolInfo
        /// </summary>
        [Fact]
        public void PresetPayToolInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PresetPayToolInfo
            //Assert.IsType<PresetPayToolInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'AssertTypeCode'
        /// </summary>
        [Fact]
        public void AssertTypeCodeTest()
        {
            // TODO unit test for the property 'AssertTypeCode'
        }
    }
}
