/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RefundSubFee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RefundSubFeeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RefundSubFee
        //private RefundSubFee instance;

        public RefundSubFeeTests()
        {
            // TODO uncomment below to create an instance of RefundSubFee
            //instance = new RefundSubFee();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RefundSubFee
        /// </summary>
        [Fact]
        public void RefundSubFeeInstanceTest()
        {
            // TODO uncomment below to test "IsType" RefundSubFee
            //Assert.IsType<RefundSubFee>(instance);
        }

        /// <summary>
        /// Test the property 'RefundChargeFee'
        /// </summary>
        [Fact]
        public void RefundChargeFeeTest()
        {
            // TODO unit test for the property 'RefundChargeFee'
        }

        /// <summary>
        /// Test the property 'SwitchFeeRate'
        /// </summary>
        [Fact]
        public void SwitchFeeRateTest()
        {
            // TODO unit test for the property 'SwitchFeeRate'
        }
    }
}
