/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SubFee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubFeeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubFee
        //private SubFee instance;

        public SubFeeTests()
        {
            // TODO uncomment below to create an instance of SubFee
            //instance = new SubFee();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubFee
        /// </summary>
        [Fact]
        public void SubFeeInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubFee
            //Assert.IsType<SubFee>(instance);
        }

        /// <summary>
        /// Test the property 'ChargeFee'
        /// </summary>
        [Fact]
        public void ChargeFeeTest()
        {
            // TODO unit test for the property 'ChargeFee'
        }

        /// <summary>
        /// Test the property 'OriginalChargeFee'
        /// </summary>
        [Fact]
        public void OriginalChargeFeeTest()
        {
            // TODO unit test for the property 'OriginalChargeFee'
        }

        /// <summary>
        /// Test the property 'SwitchFeeRate'
        /// </summary>
        [Fact]
        public void SwitchFeeRateTest()
        {
            // TODO unit test for the property 'SwitchFeeRate'
        }
    }
}
