/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TradeFundBill
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TradeFundBillTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TradeFundBill
        //private TradeFundBill instance;

        public TradeFundBillTests()
        {
            // TODO uncomment below to create an instance of TradeFundBill
            //instance = new TradeFundBill();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TradeFundBill
        /// </summary>
        [Fact]
        public void TradeFundBillInstanceTest()
        {
            // TODO uncomment below to test "IsType" TradeFundBill
            //Assert.IsType<TradeFundBill>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'BankCode'
        /// </summary>
        [Fact]
        public void BankCodeTest()
        {
            // TODO unit test for the property 'BankCode'
        }

        /// <summary>
        /// Test the property 'FundChannel'
        /// </summary>
        [Fact]
        public void FundChannelTest()
        {
            // TODO unit test for the property 'FundChannel'
        }

        /// <summary>
        /// Test the property 'FundType'
        /// </summary>
        [Fact]
        public void FundTypeTest()
        {
            // TODO unit test for the property 'FundType'
        }

        /// <summary>
        /// Test the property 'RealAmount'
        /// </summary>
        [Fact]
        public void RealAmountTest()
        {
            // TODO unit test for the property 'RealAmount'
        }
    }
}
