/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UnionIDSignUpRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UnionIDSignUpRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UnionIDSignUpRequest
        //private UnionIDSignUpRequest instance;

        public UnionIDSignUpRequestTests()
        {
            // TODO uncomment below to create an instance of UnionIDSignUpRequest
            //instance = new UnionIDSignUpRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UnionIDSignUpRequest
        /// </summary>
        [Fact]
        public void UnionIDSignUpRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UnionIDSignUpRequest
            //Assert.IsType<UnionIDSignUpRequest>(instance);
        }

        /// <summary>
        /// Test the property 'UnionID'
        /// </summary>
        [Fact]
        public void UnionIDTest()
        {
            // TODO unit test for the property 'UnionID'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'Pwd'
        /// </summary>
        [Fact]
        public void PwdTest()
        {
            // TODO unit test for the property 'Pwd'
        }

        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

        /// <summary>
        /// Test the property 'NickName'
        /// </summary>
        [Fact]
        public void NickNameTest()
        {
            // TODO unit test for the property 'NickName'
        }

        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Fact]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'EmailCode'
        /// </summary>
        [Fact]
        public void EmailCodeTest()
        {
            // TODO unit test for the property 'EmailCode'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'PhoneCode'
        /// </summary>
        [Fact]
        public void PhoneCodeTest()
        {
            // TODO unit test for the property 'PhoneCode'
        }
    }
}
