/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateProfileRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateProfileRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateProfileRequest
        //private UpdateProfileRequest instance;

        public UpdateProfileRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateProfileRequest
            //instance = new UpdateProfileRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateProfileRequest
        /// </summary>
        [Fact]
        public void UpdateProfileRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateProfileRequest
            //Assert.IsType<UpdateProfileRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Fact]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'NickName'
        /// </summary>
        [Fact]
        public void NickNameTest()
        {
            // TODO unit test for the property 'NickName'
        }

        /// <summary>
        /// Test the property 'InterestTags'
        /// </summary>
        [Fact]
        public void InterestTagsTest()
        {
            // TODO unit test for the property 'InterestTags'
        }

        /// <summary>
        /// Test the property 'Biography'
        /// </summary>
        [Fact]
        public void BiographyTest()
        {
            // TODO unit test for the property 'Biography'
        }

        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }

        /// <summary>
        /// Test the property 'Birthday'
        /// </summary>
        [Fact]
        public void BirthdayTest()
        {
            // TODO unit test for the property 'Birthday'
        }

        /// <summary>
        /// Test the property 'Occupation'
        /// </summary>
        [Fact]
        public void OccupationTest()
        {
            // TODO unit test for the property 'Occupation'
        }

        /// <summary>
        /// Test the property 'Education'
        /// </summary>
        [Fact]
        public void EducationTest()
        {
            // TODO unit test for the property 'Education'
        }

        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Fact]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }

        /// <summary>
        /// Test the property 'Languages'
        /// </summary>
        [Fact]
        public void LanguagesTest()
        {
            // TODO unit test for the property 'Languages'
        }

        /// <summary>
        /// Test the property 'SocialLinks'
        /// </summary>
        [Fact]
        public void SocialLinksTest()
        {
            // TODO unit test for the property 'SocialLinks'
        }

        /// <summary>
        /// Test the property 'RelationshipStatus'
        /// </summary>
        [Fact]
        public void RelationshipStatusTest()
        {
            // TODO unit test for the property 'RelationshipStatus'
        }

        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Fact]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }

        /// <summary>
        /// Test the property 'Industry'
        /// </summary>
        [Fact]
        public void IndustryTest()
        {
            // TODO unit test for the property 'Industry'
        }

        /// <summary>
        /// Test the property 'CompanyPosition'
        /// </summary>
        [Fact]
        public void CompanyPositionTest()
        {
            // TODO unit test for the property 'CompanyPosition'
        }

        /// <summary>
        /// Test the property 'PrivateSettings'
        /// </summary>
        [Fact]
        public void PrivateSettingsTest()
        {
            // TODO unit test for the property 'PrivateSettings'
        }

        /// <summary>
        /// Test the property 'Enable2FAAuth'
        /// </summary>
        [Fact]
        public void Enable2FAAuthTest()
        {
            // TODO unit test for the property 'Enable2FAAuth'
        }

        /// <summary>
        /// Test the property 'EnableUserNameSignIn'
        /// </summary>
        [Fact]
        public void EnableUserNameSignInTest()
        {
            // TODO unit test for the property 'EnableUserNameSignIn'
        }

        /// <summary>
        /// Test the property 'EnableEmailSignIn'
        /// </summary>
        [Fact]
        public void EnableEmailSignInTest()
        {
            // TODO unit test for the property 'EnableEmailSignIn'
        }

        /// <summary>
        /// Test the property 'EnablePhoneSignIn'
        /// </summary>
        [Fact]
        public void EnablePhoneSignInTest()
        {
            // TODO unit test for the property 'EnablePhoneSignIn'
        }

        /// <summary>
        /// Test the property 'EnableUnionIDSignIn'
        /// </summary>
        [Fact]
        public void EnableUnionIDSignInTest()
        {
            // TODO unit test for the property 'EnableUnionIDSignIn'
        }

        /// <summary>
        /// Test the property 'EnableOAuth'
        /// </summary>
        [Fact]
        public void EnableOAuthTest()
        {
            // TODO unit test for the property 'EnableOAuth'
        }
    }
}
