/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing WechatJSConfigResultApiResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WechatJSConfigResultApiResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WechatJSConfigResultApiResponse
        //private WechatJSConfigResultApiResponse instance;

        public WechatJSConfigResultApiResponseTests()
        {
            // TODO uncomment below to create an instance of WechatJSConfigResultApiResponse
            //instance = new WechatJSConfigResultApiResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WechatJSConfigResultApiResponse
        /// </summary>
        [Fact]
        public void WechatJSConfigResultApiResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WechatJSConfigResultApiResponse
            //Assert.IsType<WechatJSConfigResultApiResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
