/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ZSGF.Client.Model;
using ZSGF.Client.Client;
using System.Reflection;

namespace ZSGF.Client.Test.Model
{
    /// <summary>
    ///  Class for testing WechatJSConfigResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WechatJSConfigResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WechatJSConfigResult
        //private WechatJSConfigResult instance;

        public WechatJSConfigResultTests()
        {
            // TODO uncomment below to create an instance of WechatJSConfigResult
            //instance = new WechatJSConfigResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WechatJSConfigResult
        /// </summary>
        [Fact]
        public void WechatJSConfigResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" WechatJSConfigResult
            //Assert.IsType<WechatJSConfigResult>(instance);
        }

        /// <summary>
        /// Test the property 'Noncestr'
        /// </summary>
        [Fact]
        public void NoncestrTest()
        {
            // TODO unit test for the property 'Noncestr'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Fact]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }

        /// <summary>
        /// Test the property 'AppKey'
        /// </summary>
        [Fact]
        public void AppKeyTest()
        {
            // TODO unit test for the property 'AppKey'
        }

        /// <summary>
        /// Test the property 'JsApiList'
        /// </summary>
        [Fact]
        public void JsApiListTest()
        {
            // TODO unit test for the property 'JsApiList'
        }
    }
}
