// <auto-generated>
/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using ZSGF.Client.Client;
using ZSGF.Client.Model;

namespace ZSGF.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface ITenantFileApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        TenantFileApiEvents Events { get; }

        /// <summary>
        /// 创建文件夹
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="path"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileCreateFolderApiResponse"/>&gt;</returns>
        Task<ITenantFileCreateFolderApiResponse> TenantFileCreateFolderAsync(Option<string> path = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 创建文件夹
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="path"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileCreateFolderApiResponse"/>&gt;</returns>
        Task<ITenantFileCreateFolderApiResponse> TenantFileCreateFolderOrDefaultAsync(Option<string> path = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 删除文件
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">文件路径 (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileDeleteApiResponse"/>&gt;</returns>
        Task<ITenantFileDeleteApiResponse> TenantFileDeleteAsync(Option<string> path = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 删除文件
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="path">文件路径 (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileDeleteApiResponse"/>&gt;</returns>
        Task<ITenantFileDeleteApiResponse> TenantFileDeleteOrDefaultAsync(Option<string> path = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 重命名文件
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sourceName"> (optional)</param>
        /// <param name="destName"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileRenameApiResponse"/>&gt;</returns>
        Task<ITenantFileRenameApiResponse> TenantFileRenameAsync(Option<string> sourceName = default, Option<string> destName = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 重命名文件
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="sourceName"> (optional)</param>
        /// <param name="destName"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileRenameApiResponse"/>&gt;</returns>
        Task<ITenantFileRenameApiResponse> TenantFileRenameOrDefaultAsync(Option<string> sourceName = default, Option<string> destName = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 上传文件
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">上传的路径 (optional)</param>
        /// <param name="file">上传的文件 (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileUploadApiResponse"/>&gt;</returns>
        Task<ITenantFileUploadApiResponse> TenantFileUploadAsync(Option<string> path = default, Option<System.IO.Stream> file = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 上传文件
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="path">上传的路径 (optional)</param>
        /// <param name="file">上传的文件 (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileUploadApiResponse"/>&gt;</returns>
        Task<ITenantFileUploadApiResponse> TenantFileUploadOrDefaultAsync(Option<string> path = default, Option<System.IO.Stream> file = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 文件列表
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="path"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFilesApiResponse"/>&gt;</returns>
        Task<ITenantFilesApiResponse> TenantFilesAsync(Option<string> path = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 文件列表
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="path"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFilesApiResponse"/>&gt;</returns>
        Task<ITenantFilesApiResponse> TenantFilesOrDefaultAsync(Option<string> path = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="ITenantFileCreateFolderApiResponse"/>
    /// </summary>
    public interface ITenantFileCreateFolderApiResponse : ZSGF.Client.Client.IApiResponse, IOk<ZSGF.Client.Model.JObjectApiResult>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="ITenantFileDeleteApiResponse"/>
    /// </summary>
    public interface ITenantFileDeleteApiResponse : ZSGF.Client.Client.IApiResponse, IOk<ZSGF.Client.Model.JObjectApiResult>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="ITenantFileRenameApiResponse"/>
    /// </summary>
    public interface ITenantFileRenameApiResponse : ZSGF.Client.Client.IApiResponse, IOk<ZSGF.Client.Model.JObjectApiResult>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="ITenantFileUploadApiResponse"/>
    /// </summary>
    public interface ITenantFileUploadApiResponse : ZSGF.Client.Client.IApiResponse, IOk<ZSGF.Client.Model.JObjectApiResult>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="ITenantFilesApiResponse"/>
    /// </summary>
    public interface ITenantFilesApiResponse : ZSGF.Client.Client.IApiResponse, IOk<ZSGF.Client.Model.JObjectApiResult>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class TenantFileApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs> OnTenantFileCreateFolder;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs> OnErrorTenantFileCreateFolder;

        internal void ExecuteOnTenantFileCreateFolder(TenantFileApi.TenantFileCreateFolderApiResponse apiResponse)
        {
            OnTenantFileCreateFolder?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorTenantFileCreateFolder(Exception exception)
        {
            OnErrorTenantFileCreateFolder?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs> OnTenantFileDelete;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs> OnErrorTenantFileDelete;

        internal void ExecuteOnTenantFileDelete(TenantFileApi.TenantFileDeleteApiResponse apiResponse)
        {
            OnTenantFileDelete?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorTenantFileDelete(Exception exception)
        {
            OnErrorTenantFileDelete?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs> OnTenantFileRename;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs> OnErrorTenantFileRename;

        internal void ExecuteOnTenantFileRename(TenantFileApi.TenantFileRenameApiResponse apiResponse)
        {
            OnTenantFileRename?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorTenantFileRename(Exception exception)
        {
            OnErrorTenantFileRename?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs> OnTenantFileUpload;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs> OnErrorTenantFileUpload;

        internal void ExecuteOnTenantFileUpload(TenantFileApi.TenantFileUploadApiResponse apiResponse)
        {
            OnTenantFileUpload?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorTenantFileUpload(Exception exception)
        {
            OnErrorTenantFileUpload?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs> OnTenantFiles;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs> OnErrorTenantFiles;

        internal void ExecuteOnTenantFiles(TenantFileApi.TenantFilesApiResponse apiResponse)
        {
            OnTenantFiles?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorTenantFiles(Exception exception)
        {
            OnErrorTenantFiles?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class TenantFileApi : ITenantFileApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<TenantFileApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public TenantFileApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="BearerToken"/>
        /// </summary>
        public TokenProvider<BearerToken> BearerTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="TenantFileApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TenantFileApi(ILogger<TenantFileApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, TenantFileApiEvents tenantFileApiEvents,
            TokenProvider<BearerToken> bearerTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<TenantFileApi>();
            HttpClient = httpClient;
            Events = tenantFileApiEvents;
            BearerTokenProvider = bearerTokenProvider;
        }

        partial void FormatTenantFileCreateFolder(ref Option<string> path);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="path"></param>
        /// <returns></returns>
        private void ValidateTenantFileCreateFolder(Option<string> path)
        {
            if (path.IsSet && path.Value == null)
                throw new ArgumentNullException(nameof(path));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="path"></param>
        private void AfterTenantFileCreateFolderDefaultImplementation(ITenantFileCreateFolderApiResponse apiResponseLocalVar, Option<string> path)
        {
            bool suppressDefaultLog = false;
            AfterTenantFileCreateFolder(ref suppressDefaultLog, apiResponseLocalVar, path);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="path"></param>
        partial void AfterTenantFileCreateFolder(ref bool suppressDefaultLog, ITenantFileCreateFolderApiResponse apiResponseLocalVar, Option<string> path);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="path"></param>
        private void OnErrorTenantFileCreateFolderDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> path)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorTenantFileCreateFolder(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, path);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="path"></param>
        partial void OnErrorTenantFileCreateFolder(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> path);

        /// <summary>
        /// 创建文件夹 
        /// </summary>
        /// <param name="path"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileCreateFolderApiResponse"/>&gt;</returns>
        public async Task<ITenantFileCreateFolderApiResponse> TenantFileCreateFolderOrDefaultAsync(Option<string> path = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await TenantFileCreateFolderAsync(path, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// 创建文件夹 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="path"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileCreateFolderApiResponse"/>&gt;</returns>
        public async Task<ITenantFileCreateFolderApiResponse> TenantFileCreateFolderAsync(Option<string> path = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateTenantFileCreateFolder(path);

                FormatTenantFileCreateFolder(ref path);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = ClientUtils.CONTEXT_PATH + "/TenantFile/CreateFolder";

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (path.IsSet)
                        parseQueryStringLocalVar["path"] = ClientUtils.ParameterToString(path.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));
                    httpRequestMessageLocalVar.Method = new HttpMethod("POST");

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync().ConfigureAwait(false);

                        ILogger<TenantFileCreateFolderApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<TenantFileCreateFolderApiResponse>();

                        TenantFileCreateFolderApiResponse apiResponseLocalVar = new TenantFileCreateFolderApiResponse(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/TenantFile/CreateFolder", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterTenantFileCreateFolderDefaultImplementation(apiResponseLocalVar, path);

                        Events.ExecuteOnTenantFileCreateFolder(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorTenantFileCreateFolderDefaultImplementation(e, "/TenantFile/CreateFolder", uriBuilderLocalVar.Path, path);
                Events.ExecuteOnErrorTenantFileCreateFolder(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="TenantFileCreateFolderApiResponse"/>
        /// </summary>
        public partial class TenantFileCreateFolderApiResponse : ZSGF.Client.Client.ApiResponse, ITenantFileCreateFolderApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<TenantFileCreateFolderApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="TenantFileCreateFolderApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public TenantFileCreateFolderApiResponse(ILogger<TenantFileCreateFolderApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public ZSGF.Client.Model.JObjectApiResult Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<ZSGF.Client.Model.JObjectApiResult>(RawContent, _jsonSerializerOptions)
                    : default;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk(out ZSGF.Client.Model.JObjectApiResult result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatTenantFileDelete(ref Option<string> path);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="path"></param>
        /// <returns></returns>
        private void ValidateTenantFileDelete(Option<string> path)
        {
            if (path.IsSet && path.Value == null)
                throw new ArgumentNullException(nameof(path));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="path"></param>
        private void AfterTenantFileDeleteDefaultImplementation(ITenantFileDeleteApiResponse apiResponseLocalVar, Option<string> path)
        {
            bool suppressDefaultLog = false;
            AfterTenantFileDelete(ref suppressDefaultLog, apiResponseLocalVar, path);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="path"></param>
        partial void AfterTenantFileDelete(ref bool suppressDefaultLog, ITenantFileDeleteApiResponse apiResponseLocalVar, Option<string> path);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="path"></param>
        private void OnErrorTenantFileDeleteDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> path)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorTenantFileDelete(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, path);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="path"></param>
        partial void OnErrorTenantFileDelete(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> path);

        /// <summary>
        /// 删除文件 
        /// </summary>
        /// <param name="path">文件路径 (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileDeleteApiResponse"/>&gt;</returns>
        public async Task<ITenantFileDeleteApiResponse> TenantFileDeleteOrDefaultAsync(Option<string> path = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await TenantFileDeleteAsync(path, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// 删除文件 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">文件路径 (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileDeleteApiResponse"/>&gt;</returns>
        public async Task<ITenantFileDeleteApiResponse> TenantFileDeleteAsync(Option<string> path = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateTenantFileDelete(path);

                FormatTenantFileDelete(ref path);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = ClientUtils.CONTEXT_PATH + "/TenantFile";

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (path.IsSet)
                        parseQueryStringLocalVar["path"] = ClientUtils.ParameterToString(path.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));
                    httpRequestMessageLocalVar.Method = new HttpMethod("DELETE");

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync().ConfigureAwait(false);

                        ILogger<TenantFileDeleteApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<TenantFileDeleteApiResponse>();

                        TenantFileDeleteApiResponse apiResponseLocalVar = new TenantFileDeleteApiResponse(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/TenantFile", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterTenantFileDeleteDefaultImplementation(apiResponseLocalVar, path);

                        Events.ExecuteOnTenantFileDelete(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorTenantFileDeleteDefaultImplementation(e, "/TenantFile", uriBuilderLocalVar.Path, path);
                Events.ExecuteOnErrorTenantFileDelete(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="TenantFileDeleteApiResponse"/>
        /// </summary>
        public partial class TenantFileDeleteApiResponse : ZSGF.Client.Client.ApiResponse, ITenantFileDeleteApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<TenantFileDeleteApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="TenantFileDeleteApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public TenantFileDeleteApiResponse(ILogger<TenantFileDeleteApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public ZSGF.Client.Model.JObjectApiResult Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<ZSGF.Client.Model.JObjectApiResult>(RawContent, _jsonSerializerOptions)
                    : default;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk(out ZSGF.Client.Model.JObjectApiResult result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatTenantFileRename(ref Option<string> sourceName, ref Option<string> destName);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="sourceName"></param>
        /// <param name="destName"></param>
        /// <returns></returns>
        private void ValidateTenantFileRename(Option<string> sourceName, Option<string> destName)
        {
            if (sourceName.IsSet && sourceName.Value == null)
                throw new ArgumentNullException(nameof(sourceName));

            if (destName.IsSet && destName.Value == null)
                throw new ArgumentNullException(nameof(destName));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="sourceName"></param>
        /// <param name="destName"></param>
        private void AfterTenantFileRenameDefaultImplementation(ITenantFileRenameApiResponse apiResponseLocalVar, Option<string> sourceName, Option<string> destName)
        {
            bool suppressDefaultLog = false;
            AfterTenantFileRename(ref suppressDefaultLog, apiResponseLocalVar, sourceName, destName);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="sourceName"></param>
        /// <param name="destName"></param>
        partial void AfterTenantFileRename(ref bool suppressDefaultLog, ITenantFileRenameApiResponse apiResponseLocalVar, Option<string> sourceName, Option<string> destName);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="sourceName"></param>
        /// <param name="destName"></param>
        private void OnErrorTenantFileRenameDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> sourceName, Option<string> destName)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorTenantFileRename(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, sourceName, destName);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="sourceName"></param>
        /// <param name="destName"></param>
        partial void OnErrorTenantFileRename(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> sourceName, Option<string> destName);

        /// <summary>
        /// 重命名文件 
        /// </summary>
        /// <param name="sourceName"> (optional)</param>
        /// <param name="destName"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileRenameApiResponse"/>&gt;</returns>
        public async Task<ITenantFileRenameApiResponse> TenantFileRenameOrDefaultAsync(Option<string> sourceName = default, Option<string> destName = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await TenantFileRenameAsync(sourceName, destName, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// 重命名文件 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sourceName"> (optional)</param>
        /// <param name="destName"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileRenameApiResponse"/>&gt;</returns>
        public async Task<ITenantFileRenameApiResponse> TenantFileRenameAsync(Option<string> sourceName = default, Option<string> destName = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateTenantFileRename(sourceName, destName);

                FormatTenantFileRename(ref sourceName, ref destName);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = ClientUtils.CONTEXT_PATH + "/TenantFile/Rename";

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (sourceName.IsSet)
                        parseQueryStringLocalVar["sourceName"] = ClientUtils.ParameterToString(sourceName.Value);

                    if (destName.IsSet)
                        parseQueryStringLocalVar["destName"] = ClientUtils.ParameterToString(destName.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));
                    httpRequestMessageLocalVar.Method = new HttpMethod("POST");

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync().ConfigureAwait(false);

                        ILogger<TenantFileRenameApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<TenantFileRenameApiResponse>();

                        TenantFileRenameApiResponse apiResponseLocalVar = new TenantFileRenameApiResponse(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/TenantFile/Rename", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterTenantFileRenameDefaultImplementation(apiResponseLocalVar, sourceName, destName);

                        Events.ExecuteOnTenantFileRename(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorTenantFileRenameDefaultImplementation(e, "/TenantFile/Rename", uriBuilderLocalVar.Path, sourceName, destName);
                Events.ExecuteOnErrorTenantFileRename(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="TenantFileRenameApiResponse"/>
        /// </summary>
        public partial class TenantFileRenameApiResponse : ZSGF.Client.Client.ApiResponse, ITenantFileRenameApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<TenantFileRenameApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="TenantFileRenameApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public TenantFileRenameApiResponse(ILogger<TenantFileRenameApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public ZSGF.Client.Model.JObjectApiResult Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<ZSGF.Client.Model.JObjectApiResult>(RawContent, _jsonSerializerOptions)
                    : default;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk(out ZSGF.Client.Model.JObjectApiResult result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatTenantFileUpload(ref Option<string> path, ref Option<System.IO.Stream> file);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="path"></param>
        /// <param name="file"></param>
        /// <returns></returns>
        private void ValidateTenantFileUpload(Option<string> path, Option<System.IO.Stream> file)
        {
            if (path.IsSet && path.Value == null)
                throw new ArgumentNullException(nameof(path));

            if (file.IsSet && file.Value == null)
                throw new ArgumentNullException(nameof(file));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="path"></param>
        /// <param name="file"></param>
        private void AfterTenantFileUploadDefaultImplementation(ITenantFileUploadApiResponse apiResponseLocalVar, Option<string> path, Option<System.IO.Stream> file)
        {
            bool suppressDefaultLog = false;
            AfterTenantFileUpload(ref suppressDefaultLog, apiResponseLocalVar, path, file);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="path"></param>
        /// <param name="file"></param>
        partial void AfterTenantFileUpload(ref bool suppressDefaultLog, ITenantFileUploadApiResponse apiResponseLocalVar, Option<string> path, Option<System.IO.Stream> file);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="path"></param>
        /// <param name="file"></param>
        private void OnErrorTenantFileUploadDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> path, Option<System.IO.Stream> file)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorTenantFileUpload(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, path, file);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="path"></param>
        /// <param name="file"></param>
        partial void OnErrorTenantFileUpload(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> path, Option<System.IO.Stream> file);

        /// <summary>
        /// 上传文件 
        /// </summary>
        /// <param name="path">上传的路径 (optional)</param>
        /// <param name="file">上传的文件 (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileUploadApiResponse"/>&gt;</returns>
        public async Task<ITenantFileUploadApiResponse> TenantFileUploadOrDefaultAsync(Option<string> path = default, Option<System.IO.Stream> file = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await TenantFileUploadAsync(path, file, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// 上传文件 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="path">上传的路径 (optional)</param>
        /// <param name="file">上传的文件 (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFileUploadApiResponse"/>&gt;</returns>
        public async Task<ITenantFileUploadApiResponse> TenantFileUploadAsync(Option<string> path = default, Option<System.IO.Stream> file = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateTenantFileUpload(path, file);

                FormatTenantFileUpload(ref path, ref file);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = ClientUtils.CONTEXT_PATH + "/TenantFile";

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (path.IsSet)
                        parseQueryStringLocalVar["path"] = ClientUtils.ParameterToString(path.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    MultipartContent multipartContentLocalVar = new MultipartContent();

                    httpRequestMessageLocalVar.Content = multipartContentLocalVar;

                    List<KeyValuePair<string, string>> formParameterLocalVars = new List<KeyValuePair<string, string>>();

                    multipartContentLocalVar.Add(new FormUrlEncodedContent(formParameterLocalVars));                    if (file.IsSet)
                        multipartContentLocalVar.Add(new StreamContent(file.Value));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] contentTypes = new string[] {
                        "multipart/form-data"
                    };

                    string contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));
                    httpRequestMessageLocalVar.Method = new HttpMethod("POST");

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync().ConfigureAwait(false);

                        ILogger<TenantFileUploadApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<TenantFileUploadApiResponse>();

                        TenantFileUploadApiResponse apiResponseLocalVar = new TenantFileUploadApiResponse(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/TenantFile", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterTenantFileUploadDefaultImplementation(apiResponseLocalVar, path, file);

                        Events.ExecuteOnTenantFileUpload(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorTenantFileUploadDefaultImplementation(e, "/TenantFile", uriBuilderLocalVar.Path, path, file);
                Events.ExecuteOnErrorTenantFileUpload(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="TenantFileUploadApiResponse"/>
        /// </summary>
        public partial class TenantFileUploadApiResponse : ZSGF.Client.Client.ApiResponse, ITenantFileUploadApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<TenantFileUploadApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="TenantFileUploadApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public TenantFileUploadApiResponse(ILogger<TenantFileUploadApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public ZSGF.Client.Model.JObjectApiResult Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<ZSGF.Client.Model.JObjectApiResult>(RawContent, _jsonSerializerOptions)
                    : default;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk(out ZSGF.Client.Model.JObjectApiResult result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatTenantFiles(ref Option<string> path);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="path"></param>
        /// <returns></returns>
        private void ValidateTenantFiles(Option<string> path)
        {
            if (path.IsSet && path.Value == null)
                throw new ArgumentNullException(nameof(path));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="path"></param>
        private void AfterTenantFilesDefaultImplementation(ITenantFilesApiResponse apiResponseLocalVar, Option<string> path)
        {
            bool suppressDefaultLog = false;
            AfterTenantFiles(ref suppressDefaultLog, apiResponseLocalVar, path);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="path"></param>
        partial void AfterTenantFiles(ref bool suppressDefaultLog, ITenantFilesApiResponse apiResponseLocalVar, Option<string> path);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="path"></param>
        private void OnErrorTenantFilesDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> path)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorTenantFiles(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, path);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="path"></param>
        partial void OnErrorTenantFiles(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> path);

        /// <summary>
        /// 文件列表 
        /// </summary>
        /// <param name="path"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFilesApiResponse"/>&gt;</returns>
        public async Task<ITenantFilesApiResponse> TenantFilesOrDefaultAsync(Option<string> path = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await TenantFilesAsync(path, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// 文件列表 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="path"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITenantFilesApiResponse"/>&gt;</returns>
        public async Task<ITenantFilesApiResponse> TenantFilesAsync(Option<string> path = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateTenantFiles(path);

                FormatTenantFiles(ref path);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = ClientUtils.CONTEXT_PATH + "/TenantFile";

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (path.IsSet)
                        parseQueryStringLocalVar["path"] = ClientUtils.ParameterToString(path.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));
                    httpRequestMessageLocalVar.Method = new HttpMethod("GET");

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync().ConfigureAwait(false);

                        ILogger<TenantFilesApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<TenantFilesApiResponse>();

                        TenantFilesApiResponse apiResponseLocalVar = new TenantFilesApiResponse(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/TenantFile", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterTenantFilesDefaultImplementation(apiResponseLocalVar, path);

                        Events.ExecuteOnTenantFiles(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorTenantFilesDefaultImplementation(e, "/TenantFile", uriBuilderLocalVar.Path, path);
                Events.ExecuteOnErrorTenantFiles(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="TenantFilesApiResponse"/>
        /// </summary>
        public partial class TenantFilesApiResponse : ZSGF.Client.Client.ApiResponse, ITenantFilesApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<TenantFilesApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="TenantFilesApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public TenantFilesApiResponse(ILogger<TenantFilesApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public ZSGF.Client.Model.JObjectApiResult Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<ZSGF.Client.Model.JObjectApiResult>(RawContent, _jsonSerializerOptions)
                    : default;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk(out ZSGF.Client.Model.JObjectApiResult result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
