/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using ZSGF.Client.Api;
using ZSGF.Client.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace ZSGF.Client.Test.Api
{
    /// <summary>
    ///  Class for testing AppSettingApi
    /// </summary>
    public sealed class AppSettingApiTests : ApiTestsBase
    {
        private readonly IAppSettingApi _instance;

        public AppSettingApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IAppSettingApi>();
        }

        /// <summary>
        /// Test AppServiceSettingGroup
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingGroupAsyncTest()
        {
            long id = default;
            string appKey = default;
            var response = await _instance.AppServiceSettingGroupAsync(id, appKey);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingGroupDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingGroupDeleteAsyncTest()
        {
            long id = default;
            string appKey = default;
            var response = await _instance.AppServiceSettingGroupDeleteAsync(id, appKey);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingGroupPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingGroupPostAsyncTest()
        {
            string appKey = default;
            Client.Option<ServiceGroup> serviceGroup = default;
            var response = await _instance.AppServiceSettingGroupPostAsync(appKey, serviceGroup);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingGroupPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingGroupPutAsyncTest()
        {
            long id = default;
            string appKey = default;
            Client.Option<ServiceGroup> serviceGroup = default;
            var response = await _instance.AppServiceSettingGroupPutAsync(id, appKey, serviceGroup);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingGroups
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingGroupsAsyncTest()
        {
            string appKey = default;
            Client.Option<long> providerId = default;
            Client.Option<bool> showFlag = default;
            var response = await _instance.AppServiceSettingGroupsAsync(appKey, providerId, showFlag);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingItem
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingItemAsyncTest()
        {
            long id = default;
            string appKey = default;
            var response = await _instance.AppServiceSettingItemAsync(id, appKey);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingItemDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingItemDeleteAsyncTest()
        {
            long id = default;
            string appKey = default;
            var response = await _instance.AppServiceSettingItemDeleteAsync(id, appKey);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingItemPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingItemPostAsyncTest()
        {
            string appKey = default;
            Client.Option<ServiceItem> serviceItem = default;
            var response = await _instance.AppServiceSettingItemPostAsync(appKey, serviceItem);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingItemPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingItemPutAsyncTest()
        {
            long id = default;
            string appKey = default;
            Client.Option<ServiceItem> serviceItem = default;
            var response = await _instance.AppServiceSettingItemPutAsync(id, appKey, serviceItem);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingItems
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingItemsAsyncTest()
        {
            string appKey = default;
            Client.Option<string> bizCode = default;
            Client.Option<string> providerCode = default;
            Client.Option<string> groupCode = default;
            Client.Option<bool> showFlag = default;
            var response = await _instance.AppServiceSettingItemsAsync(appKey, bizCode, providerCode, groupCode, showFlag);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingProvider
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingProviderAsyncTest()
        {
            long id = default;
            string appKey = default;
            var response = await _instance.AppServiceSettingProviderAsync(id, appKey);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingProviderDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingProviderDeleteAsyncTest()
        {
            long id = default;
            string appKey = default;
            var response = await _instance.AppServiceSettingProviderDeleteAsync(id, appKey);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingProviderPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingProviderPostAsyncTest()
        {
            string appKey = default;
            Client.Option<ServiceProvider> serviceProvider = default;
            var response = await _instance.AppServiceSettingProviderPostAsync(appKey, serviceProvider);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingProviderPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingProviderPutAsyncTest()
        {
            long id = default;
            string appKey = default;
            Client.Option<ServiceProvider> serviceProvider = default;
            var response = await _instance.AppServiceSettingProviderPutAsync(id, appKey, serviceProvider);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppServiceSettingProviders
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppServiceSettingProvidersAsyncTest()
        {
            string appKey = default;
            Client.Option<string> bizCode = default;
            Client.Option<bool> showFlag = default;
            var response = await _instance.AppServiceSettingProvidersAsync(appKey, bizCode, showFlag);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppSetting
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppSettingAsyncTest()
        {
            long id = default;
            string appKey = default;
            var response = await _instance.AppSettingAsync(id, appKey);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppSettingDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppSettingDeleteAsyncTest()
        {
            long id = default;
            string appKey = default;
            var response = await _instance.AppSettingDeleteAsync(id, appKey);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppSettingPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppSettingPostAsyncTest()
        {
            string appKey = default;
            Client.Option<AppSetting> appSetting = default;
            var response = await _instance.AppSettingPostAsync(appKey, appSetting);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppSettingPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppSettingPutAsyncTest()
        {
            long id = default;
            string appKey = default;
            Client.Option<AppSetting> appSetting = default;
            var response = await _instance.AppSettingPutAsync(id, appKey, appSetting);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test AppSettings
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AppSettingsAsyncTest()
        {
            string appKey = default;
            Client.Option<string> providerCode = default;
            Client.Option<string> groupCode = default;
            Client.Option<string> tag = default;
            Client.Option<string> code = default;
            var response = await _instance.AppSettingsAsync(appKey, providerCode, groupCode, tag, code);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }
    }
}
