/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using ZSGF.Client.Api;
using ZSGF.Client.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace ZSGF.Client.Test.Api
{
    /// <summary>
    ///  Class for testing TenantApi
    /// </summary>
    public sealed class TenantApiTests : ApiTestsBase
    {
        private readonly ITenantApi _instance;

        public TenantApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ITenantApi>();
        }

        /// <summary>
        /// Test Tenant
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TenantAsyncTest()
        {
            long id = default;
            var response = await _instance.TenantAsync(id);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test TenantBackup
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TenantBackupAsyncTest()
        {
            var response = await _instance.TenantBackupAsync();
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test TenantBackupDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TenantBackupDeleteAsyncTest()
        {
            Client.Option<long> id = default;
            Client.Option<string> version = default;
            var response = await _instance.TenantBackupDeleteAsync(id, version);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test TenantBackupRemark
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TenantBackupRemarkAsyncTest()
        {
            Client.Option<string> version = default;
            var response = await _instance.TenantBackupRemarkAsync(version);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test TenantBackupRemarkPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TenantBackupRemarkPutAsyncTest()
        {
            Client.Option<string> version = default;
            Client.Option<Dictionary<string, string>> requestBody = default;
            var response = await _instance.TenantBackupRemarkPutAsync(version, requestBody);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test TenantBackups
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TenantBackupsAsyncTest()
        {
            Client.Option<int> skip = default;
            Client.Option<int> take = default;
            var response = await _instance.TenantBackupsAsync(skip, take);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test TenantCheckVersion
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TenantCheckVersionAsyncTest()
        {
            Client.Option<bool> checkOnly = default;
            var response = await _instance.TenantCheckVersionAsync(checkOnly);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test TenantPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TenantPutAsyncTest()
        {
            long id = default;
            Client.Option<Tenant> tenant = default;
            var response = await _instance.TenantPutAsync(id, tenant);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test TenantRollback
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TenantRollbackAsyncTest()
        {
            Client.Option<long> id = default;
            Client.Option<string> version = default;
            var response = await _instance.TenantRollbackAsync(id, version);
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test TenantSettings
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TenantSettingsAsyncTest()
        {
            var response = await _instance.TenantSettingsAsync();
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }

        /// <summary>
        /// Test Tenants
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TenantsAsyncTest()
        {
            var response = await _instance.TenantsAsync();
            var model = response.Ok();
            Assert.IsType<JObjectApiResult>(model);
        }
    }
}
