// <auto-generated>
/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ZSGF.Client.Client;

namespace ZSGF.Client.Model
{
    /// <summary>
    /// 应用设置
    /// </summary>
    public partial class AppSetting : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppSetting" /> class.
        /// </summary>
        /// <param name="code">设置项代码</param>
        /// <param name="value">设置值</param>
        /// <param name="id">唯一标识</param>
        /// <param name="providerCode">提供商代码</param>
        /// <param name="groupCode">分组代码</param>
        /// <param name="tags">标签</param>
        /// <param name="description">描述</param>
        /// <param name="frontendUsable">是否在前端可用</param>
        /// <param name="createDate">创建时间</param>
        /// <param name="lastUpdate">最后更新时间</param>
        [JsonConstructor]
        public AppSetting(string code, string value, Option<long?> id = default, Option<string> providerCode = default, Option<string> groupCode = default, Option<string> tags = default, Option<string> description = default, Option<bool?> frontendUsable = default, Option<DateTime?> createDate = default, Option<DateTime?> lastUpdate = default)
        {
            Code = code;
            Value = value;
            IdOption = id;
            ProviderCodeOption = providerCode;
            GroupCodeOption = groupCode;
            TagsOption = tags;
            DescriptionOption = description;
            FrontendUsableOption = frontendUsable;
            CreateDateOption = createDate;
            LastUpdateOption = lastUpdate;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// 设置项代码
        /// </summary>
        /// <value>设置项代码</value>
        [JsonPropertyName("code")]
        public string Code { get; set; }

        /// <summary>
        /// 设置值
        /// </summary>
        /// <value>设置值</value>
        [JsonPropertyName("value")]
        public string Value { get; set; }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> IdOption { get; private set; }

        /// <summary>
        /// 唯一标识
        /// </summary>
        /// <value>唯一标识</value>
        [JsonPropertyName("id")]
        public long? Id { get { return this.IdOption; } set { this.IdOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of ProviderCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ProviderCodeOption { get; private set; }

        /// <summary>
        /// 提供商代码
        /// </summary>
        /// <value>提供商代码</value>
        [JsonPropertyName("providerCode")]
        public string ProviderCode { get { return this.ProviderCodeOption; } set { this.ProviderCodeOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of GroupCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> GroupCodeOption { get; private set; }

        /// <summary>
        /// 分组代码
        /// </summary>
        /// <value>分组代码</value>
        [JsonPropertyName("groupCode")]
        public string GroupCode { get { return this.GroupCodeOption; } set { this.GroupCodeOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> TagsOption { get; private set; }

        /// <summary>
        /// 标签
        /// </summary>
        /// <value>标签</value>
        [JsonPropertyName("tags")]
        public string Tags { get { return this.TagsOption; } set { this.TagsOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DescriptionOption { get; private set; }

        /// <summary>
        /// 描述
        /// </summary>
        /// <value>描述</value>
        [JsonPropertyName("description")]
        public string Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of FrontendUsable
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> FrontendUsableOption { get; private set; }

        /// <summary>
        /// 是否在前端可用
        /// </summary>
        /// <value>是否在前端可用</value>
        [JsonPropertyName("frontendUsable")]
        public bool? FrontendUsable { get { return this.FrontendUsableOption; } set { this.FrontendUsableOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of CreateDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreateDateOption { get; private set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        /// <value>创建时间</value>
        [JsonPropertyName("createDate")]
        public DateTime? CreateDate { get { return this.CreateDateOption; } set { this.CreateDateOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Used to track the state of LastUpdate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> LastUpdateOption { get; private set; }

        /// <summary>
        /// 最后更新时间
        /// </summary>
        /// <value>最后更新时间</value>
        [JsonPropertyName("lastUpdate")]
        public DateTime? LastUpdate { get { return this.LastUpdateOption; } set { this.LastUpdateOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppSetting {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ProviderCode: ").Append(ProviderCode).Append("\n");
            sb.Append("  GroupCode: ").Append(GroupCode).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  FrontendUsable: ").Append(FrontendUsable).Append("\n");
            sb.Append("  CreateDate: ").Append(CreateDate).Append("\n");
            sb.Append("  LastUpdate: ").Append(LastUpdate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Code (string) maxLength
            if (this.Code != null && this.Code.Length > 50)
            {
                yield return new ValidationResult("Invalid value for Code, length must be less than 50.", new [] { "Code" });
            }

            // Code (string) minLength
            if (this.Code != null && this.Code.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Code, length must be greater than 1.", new [] { "Code" });
            }

            // Value (string) minLength
            if (this.Value != null && this.Value.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Value, length must be greater than 1.", new [] { "Value" });
            }

            // ProviderCode (string) maxLength
            if (this.ProviderCode != null && this.ProviderCode.Length > 50)
            {
                yield return new ValidationResult("Invalid value for ProviderCode, length must be less than 50.", new [] { "ProviderCode" });
            }

            // GroupCode (string) maxLength
            if (this.GroupCode != null && this.GroupCode.Length > 50)
            {
                yield return new ValidationResult("Invalid value for GroupCode, length must be less than 50.", new [] { "GroupCode" });
            }

            // Tags (string) maxLength
            if (this.Tags != null && this.Tags.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Tags, length must be less than 255.", new [] { "Tags" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 255.", new [] { "Description" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AppSetting" />
    /// </summary>
    public class AppSettingJsonConverter : JsonConverter<AppSetting>
    {
        /// <summary>
        /// The format to use to serialize CreateDate
        /// </summary>
        public static string CreateDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize LastUpdate
        /// </summary>
        public static string LastUpdateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="AppSetting" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AppSetting Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> code = default;
            Option<string> value = default;
            Option<long?> id = default;
            Option<string> providerCode = default;
            Option<string> groupCode = default;
            Option<string> tags = default;
            Option<string> description = default;
            Option<bool?> frontendUsable = default;
            Option<DateTime?> createDate = default;
            Option<DateTime?> lastUpdate = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "code":
                            code = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "value":
                            value = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "providerCode":
                            providerCode = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "groupCode":
                            groupCode = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "tags":
                            tags = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "description":
                            description = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "frontendUsable":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                frontendUsable = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "createDate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                createDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "lastUpdate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                lastUpdate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!code.IsSet)
                throw new ArgumentException("Property is required for class AppSetting.", nameof(code));

            if (!value.IsSet)
                throw new ArgumentException("Property is required for class AppSetting.", nameof(value));

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class AppSetting.");

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class AppSetting.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class AppSetting.");

            if (frontendUsable.IsSet && frontendUsable.Value == null)
                throw new ArgumentNullException(nameof(frontendUsable), "Property is not nullable for class AppSetting.");

            if (createDate.IsSet && createDate.Value == null)
                throw new ArgumentNullException(nameof(createDate), "Property is not nullable for class AppSetting.");

            if (lastUpdate.IsSet && lastUpdate.Value == null)
                throw new ArgumentNullException(nameof(lastUpdate), "Property is not nullable for class AppSetting.");

            return new AppSetting(code.Value, value.Value, id, providerCode, groupCode, tags, description, frontendUsable, createDate, lastUpdate);
        }

        /// <summary>
        /// Serializes a <see cref="AppSetting" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="appSetting"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AppSetting appSetting, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, appSetting, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AppSetting" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="appSetting"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AppSetting appSetting, JsonSerializerOptions jsonSerializerOptions)
        {
            if (appSetting.Code == null)
                throw new ArgumentNullException(nameof(appSetting.Code), "Property is required for class AppSetting.");

            if (appSetting.Value == null)
                throw new ArgumentNullException(nameof(appSetting.Value), "Property is required for class AppSetting.");

            writer.WriteString("code", appSetting.Code);

            writer.WriteString("value", appSetting.Value);

            if (appSetting.IdOption.IsSet)
                writer.WriteNumber("id", appSetting.IdOption.Value.Value);

            if (appSetting.ProviderCodeOption.IsSet)
                if (appSetting.ProviderCodeOption.Value != null)
                    writer.WriteString("providerCode", appSetting.ProviderCode);
                else
                    writer.WriteNull("providerCode");

            if (appSetting.GroupCodeOption.IsSet)
                if (appSetting.GroupCodeOption.Value != null)
                    writer.WriteString("groupCode", appSetting.GroupCode);
                else
                    writer.WriteNull("groupCode");

            if (appSetting.TagsOption.IsSet)
                if (appSetting.TagsOption.Value != null)
                    writer.WriteString("tags", appSetting.Tags);
                else
                    writer.WriteNull("tags");

            if (appSetting.DescriptionOption.IsSet)
                if (appSetting.DescriptionOption.Value != null)
                    writer.WriteString("description", appSetting.Description);
                else
                    writer.WriteNull("description");

            if (appSetting.FrontendUsableOption.IsSet)
                writer.WriteBoolean("frontendUsable", appSetting.FrontendUsableOption.Value.Value);

            if (appSetting.CreateDateOption.IsSet)
                writer.WriteString("createDate", appSetting.CreateDateOption.Value.Value.ToString(CreateDateFormat));

            if (appSetting.LastUpdateOption.IsSet)
                writer.WriteString("lastUpdate", appSetting.LastUpdateOption.Value.Value.ToString(LastUpdateFormat));
        }
    }
}
