// <auto-generated>
/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ZSGF.Client.Client;

namespace ZSGF.Client.Model
{
    /// <summary>
    /// CurrencyConsumeRequest
    /// </summary>
    public partial class CurrencyConsumeRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrencyConsumeRequest" /> class.
        /// </summary>
        /// <param name="currency">虚拟币代码</param>
        /// <param name="balance">消费额</param>
        /// <param name="remark">备注</param>
        /// <param name="description">描述</param>
        /// <param name="tags">标签</param>
        [JsonConstructor]
        public CurrencyConsumeRequest(string currency, int balance, Option<string> remark = default, Option<string> description = default, Option<string> tags = default)
        {
            Currency = currency;
            Balance = balance;
            RemarkOption = remark;
            DescriptionOption = description;
            TagsOption = tags;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// 虚拟币代码
        /// </summary>
        /// <value>虚拟币代码</value>
        [JsonPropertyName("currency")]
        public string Currency { get; set; }

        /// <summary>
        /// 消费额
        /// </summary>
        /// <value>消费额</value>
        [JsonPropertyName("balance")]
        public int Balance { get; set; }

        /// <summary>
        /// Used to track the state of Remark
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> RemarkOption { get; private set; }

        /// <summary>
        /// 备注
        /// </summary>
        /// <value>备注</value>
        [JsonPropertyName("remark")]
        public string Remark { get { return this.RemarkOption; } set { this.RemarkOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DescriptionOption { get; private set; }

        /// <summary>
        /// 描述
        /// </summary>
        /// <value>描述</value>
        [JsonPropertyName("description")]
        public string Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> TagsOption { get; private set; }

        /// <summary>
        /// 标签
        /// </summary>
        /// <value>标签</value>
        [JsonPropertyName("tags")]
        public string Tags { get { return this.TagsOption; } set { this.TagsOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CurrencyConsumeRequest {\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Balance: ").Append(Balance).Append("\n");
            sb.Append("  Remark: ").Append(Remark).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Currency (string) minLength
            if (this.Currency != null && this.Currency.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Currency, length must be greater than 1.", new [] { "Currency" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CurrencyConsumeRequest" />
    /// </summary>
    public class CurrencyConsumeRequestJsonConverter : JsonConverter<CurrencyConsumeRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CurrencyConsumeRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CurrencyConsumeRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> currency = default;
            Option<int?> balance = default;
            Option<string> remark = default;
            Option<string> description = default;
            Option<string> tags = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "currency":
                            currency = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "balance":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                balance = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "remark":
                            remark = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "description":
                            description = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "tags":
                            tags = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!currency.IsSet)
                throw new ArgumentException("Property is required for class CurrencyConsumeRequest.", nameof(currency));

            if (!balance.IsSet)
                throw new ArgumentException("Property is required for class CurrencyConsumeRequest.", nameof(balance));

            if (currency.IsSet && currency.Value == null)
                throw new ArgumentNullException(nameof(currency), "Property is not nullable for class CurrencyConsumeRequest.");

            if (balance.IsSet && balance.Value == null)
                throw new ArgumentNullException(nameof(balance), "Property is not nullable for class CurrencyConsumeRequest.");

            return new CurrencyConsumeRequest(currency.Value, balance.Value.Value, remark, description, tags);
        }

        /// <summary>
        /// Serializes a <see cref="CurrencyConsumeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="currencyConsumeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CurrencyConsumeRequest currencyConsumeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, currencyConsumeRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CurrencyConsumeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="currencyConsumeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CurrencyConsumeRequest currencyConsumeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (currencyConsumeRequest.Currency == null)
                throw new ArgumentNullException(nameof(currencyConsumeRequest.Currency), "Property is required for class CurrencyConsumeRequest.");

            writer.WriteString("currency", currencyConsumeRequest.Currency);

            writer.WriteNumber("balance", currencyConsumeRequest.Balance);

            if (currencyConsumeRequest.RemarkOption.IsSet)
                if (currencyConsumeRequest.RemarkOption.Value != null)
                    writer.WriteString("remark", currencyConsumeRequest.Remark);
                else
                    writer.WriteNull("remark");

            if (currencyConsumeRequest.DescriptionOption.IsSet)
                if (currencyConsumeRequest.DescriptionOption.Value != null)
                    writer.WriteString("description", currencyConsumeRequest.Description);
                else
                    writer.WriteNull("description");

            if (currencyConsumeRequest.TagsOption.IsSet)
                if (currencyConsumeRequest.TagsOption.Value != null)
                    writer.WriteString("tags", currencyConsumeRequest.Tags);
                else
                    writer.WriteNull("tags");
        }
    }
}
