// <auto-generated>
/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ZSGF.Client.Client;

namespace ZSGF.Client.Model
{
    /// <summary>
    /// EmailSignInRequest
    /// </summary>
    public partial class EmailSignInRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailSignInRequest" /> class.
        /// </summary>
        /// <param name="email">用户邮箱地址</param>
        /// <param name="verifyCode">验证码，长度为4到8位的数字</param>
        /// <param name="twoFactorCode">双因素认证代码，如果启用双因素认证登录，则必填</param>
        [JsonConstructor]
        public EmailSignInRequest(string email, string verifyCode, Option<string> twoFactorCode = default)
        {
            Email = email;
            VerifyCode = verifyCode;
            TwoFactorCodeOption = twoFactorCode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// 用户邮箱地址
        /// </summary>
        /// <value>用户邮箱地址</value>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// 验证码，长度为4到8位的数字
        /// </summary>
        /// <value>验证码，长度为4到8位的数字</value>
        [JsonPropertyName("verifyCode")]
        public string VerifyCode { get; set; }

        /// <summary>
        /// Used to track the state of TwoFactorCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> TwoFactorCodeOption { get; private set; }

        /// <summary>
        /// 双因素认证代码，如果启用双因素认证登录，则必填
        /// </summary>
        /// <value>双因素认证代码，如果启用双因素认证登录，则必填</value>
        [JsonPropertyName("twoFactorCode")]
        public string TwoFactorCode { get { return this.TwoFactorCodeOption; } set { this.TwoFactorCodeOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailSignInRequest {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  VerifyCode: ").Append(VerifyCode).Append("\n");
            sb.Append("  TwoFactorCode: ").Append(TwoFactorCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Email (string) minLength
            if (this.Email != null && this.Email.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Email, length must be greater than 1.", new [] { "Email" });
            }

            // VerifyCode (string) minLength
            if (this.VerifyCode != null && this.VerifyCode.Length < 1)
            {
                yield return new ValidationResult("Invalid value for VerifyCode, length must be greater than 1.", new [] { "VerifyCode" });
            }

            if (this.VerifyCode != null) {
                // VerifyCode (string) pattern
                Regex regexVerifyCode = new Regex(@"\d{4,8}$", RegexOptions.CultureInvariant);

                if (!regexVerifyCode.Match(this.VerifyCode).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for VerifyCode, must match a pattern of " + regexVerifyCode, new [] { "VerifyCode" });
                }
            }

            // TwoFactorCode (string) maxLength
            if (this.TwoFactorCode != null && this.TwoFactorCode.Length > 6)
            {
                yield return new ValidationResult("Invalid value for TwoFactorCode, length must be less than 6.", new [] { "TwoFactorCode" });
            }

            // TwoFactorCode (string) minLength
            if (this.TwoFactorCode != null && this.TwoFactorCode.Length < 6)
            {
                yield return new ValidationResult("Invalid value for TwoFactorCode, length must be greater than 6.", new [] { "TwoFactorCode" });
            }

            if (this.TwoFactorCodeOption.Value != null) {
                // TwoFactorCode (string) pattern
                Regex regexTwoFactorCode = new Regex(@"^[0-9]*$", RegexOptions.CultureInvariant);

                if (this.TwoFactorCodeOption.Value != null &&!regexTwoFactorCode.Match(this.TwoFactorCodeOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TwoFactorCode, must match a pattern of " + regexTwoFactorCode, new [] { "TwoFactorCode" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EmailSignInRequest" />
    /// </summary>
    public class EmailSignInRequestJsonConverter : JsonConverter<EmailSignInRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="EmailSignInRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EmailSignInRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> email = default;
            Option<string> verifyCode = default;
            Option<string> twoFactorCode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "email":
                            email = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "verifyCode":
                            verifyCode = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "twoFactorCode":
                            twoFactorCode = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class EmailSignInRequest.", nameof(email));

            if (!verifyCode.IsSet)
                throw new ArgumentException("Property is required for class EmailSignInRequest.", nameof(verifyCode));

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class EmailSignInRequest.");

            if (verifyCode.IsSet && verifyCode.Value == null)
                throw new ArgumentNullException(nameof(verifyCode), "Property is not nullable for class EmailSignInRequest.");

            return new EmailSignInRequest(email.Value, verifyCode.Value, twoFactorCode);
        }

        /// <summary>
        /// Serializes a <see cref="EmailSignInRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emailSignInRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EmailSignInRequest emailSignInRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, emailSignInRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EmailSignInRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emailSignInRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EmailSignInRequest emailSignInRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (emailSignInRequest.Email == null)
                throw new ArgumentNullException(nameof(emailSignInRequest.Email), "Property is required for class EmailSignInRequest.");

            if (emailSignInRequest.VerifyCode == null)
                throw new ArgumentNullException(nameof(emailSignInRequest.VerifyCode), "Property is required for class EmailSignInRequest.");

            writer.WriteString("email", emailSignInRequest.Email);

            writer.WriteString("verifyCode", emailSignInRequest.VerifyCode);

            if (emailSignInRequest.TwoFactorCodeOption.IsSet)
                if (emailSignInRequest.TwoFactorCodeOption.Value != null)
                    writer.WriteString("twoFactorCode", emailSignInRequest.TwoFactorCode);
                else
                    writer.WriteNull("twoFactorCode");
        }
    }
}
