// <auto-generated>
/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ZSGF.Client.Client;

namespace ZSGF.Client.Model
{
    /// <summary>
    /// ExecuteFunctionRequest
    /// </summary>
    public partial class ExecuteFunctionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExecuteFunctionRequest" /> class.
        /// </summary>
        /// <param name="functionKey">函数标识</param>
        [JsonConstructor]
        public ExecuteFunctionRequest(Option<string> functionKey = default)
        {
            FunctionKeyOption = functionKey;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of FunctionKey
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> FunctionKeyOption { get; private set; }

        /// <summary>
        /// 函数标识
        /// </summary>
        /// <value>函数标识</value>
        [JsonPropertyName("functionKey")]
        public string FunctionKey { get { return this.FunctionKeyOption; } set { this.FunctionKeyOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExecuteFunctionRequest {\n");
            sb.Append("  FunctionKey: ").Append(FunctionKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExecuteFunctionRequest" />
    /// </summary>
    public class ExecuteFunctionRequestJsonConverter : JsonConverter<ExecuteFunctionRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ExecuteFunctionRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExecuteFunctionRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> functionKey = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "functionKey":
                            functionKey = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new ExecuteFunctionRequest(functionKey);
        }

        /// <summary>
        /// Serializes a <see cref="ExecuteFunctionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="executeFunctionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExecuteFunctionRequest executeFunctionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, executeFunctionRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExecuteFunctionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="executeFunctionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExecuteFunctionRequest executeFunctionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (executeFunctionRequest.FunctionKeyOption.IsSet)
                if (executeFunctionRequest.FunctionKeyOption.Value != null)
                    writer.WriteString("functionKey", executeFunctionRequest.FunctionKey);
                else
                    writer.WriteNull("functionKey");
        }
    }
}
