// <auto-generated>
/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ZSGF.Client.Client;

namespace ZSGF.Client.Model
{
    /// <summary>
    /// SignUpRequest
    /// </summary>
    public partial class SignUpRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignUpRequest" /> class.
        /// </summary>
        /// <param name="userName">用户名，长度必须在6到32个字符之间，只能包含字母、数字、下划线和连字符</param>
        /// <param name="pwd">登录密码，长度必须在6到32个字符之间，只能包含字母和数字</param>
        /// <param name="nickName">用户昵称，长度不能超过20个字符</param>
        /// <param name="avatar">用户头像URL</param>
        /// <param name="data">自定义数据</param>
        /// <param name="email">用户邮箱</param>
        /// <param name="emailCode">邮箱验证码（只有启用的邮箱验证码功能时，才需要传入），长度为4到8位的数字</param>
        /// <param name="phone">用户手机号，必须为11位数字</param>
        /// <param name="phoneCode">手机验证码（只有启用的手机验证码功能时，才需要传入），长度为4到8位的数字</param>
        [JsonConstructor]
        public SignUpRequest(string userName, string pwd, Option<string> nickName = default, Option<string> avatar = default, Option<string> data = default, Option<string> email = default, Option<string> emailCode = default, Option<string> phone = default, Option<string> phoneCode = default)
        {
            UserName = userName;
            Pwd = pwd;
            NickNameOption = nickName;
            AvatarOption = avatar;
            DataOption = data;
            EmailOption = email;
            EmailCodeOption = emailCode;
            PhoneOption = phone;
            PhoneCodeOption = phoneCode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// 用户名，长度必须在6到32个字符之间，只能包含字母、数字、下划线和连字符
        /// </summary>
        /// <value>用户名，长度必须在6到32个字符之间，只能包含字母、数字、下划线和连字符</value>
        [JsonPropertyName("userName")]
        public string UserName { get; set; }

        /// <summary>
        /// 登录密码，长度必须在6到32个字符之间，只能包含字母和数字
        /// </summary>
        /// <value>登录密码，长度必须在6到32个字符之间，只能包含字母和数字</value>
        [JsonPropertyName("pwd")]
        public string Pwd { get; set; }

        /// <summary>
        /// Used to track the state of NickName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NickNameOption { get; private set; }

        /// <summary>
        /// 用户昵称，长度不能超过20个字符
        /// </summary>
        /// <value>用户昵称，长度不能超过20个字符</value>
        [JsonPropertyName("nickName")]
        public string NickName { get { return this.NickNameOption; } set { this.NickNameOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Avatar
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> AvatarOption { get; private set; }

        /// <summary>
        /// 用户头像URL
        /// </summary>
        /// <value>用户头像URL</value>
        [JsonPropertyName("avatar")]
        public string Avatar { get { return this.AvatarOption; } set { this.AvatarOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DataOption { get; private set; }

        /// <summary>
        /// 自定义数据
        /// </summary>
        /// <value>自定义数据</value>
        [JsonPropertyName("data")]
        public string Data { get { return this.DataOption; } set { this.DataOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Email
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> EmailOption { get; private set; }

        /// <summary>
        /// 用户邮箱
        /// </summary>
        /// <value>用户邮箱</value>
        [JsonPropertyName("email")]
        public string Email { get { return this.EmailOption; } set { this.EmailOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of EmailCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> EmailCodeOption { get; private set; }

        /// <summary>
        /// 邮箱验证码（只有启用的邮箱验证码功能时，才需要传入），长度为4到8位的数字
        /// </summary>
        /// <value>邮箱验证码（只有启用的邮箱验证码功能时，才需要传入），长度为4到8位的数字</value>
        [JsonPropertyName("emailCode")]
        public string EmailCode { get { return this.EmailCodeOption; } set { this.EmailCodeOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Phone
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PhoneOption { get; private set; }

        /// <summary>
        /// 用户手机号，必须为11位数字
        /// </summary>
        /// <value>用户手机号，必须为11位数字</value>
        [JsonPropertyName("phone")]
        public string Phone { get { return this.PhoneOption; } set { this.PhoneOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of PhoneCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PhoneCodeOption { get; private set; }

        /// <summary>
        /// 手机验证码（只有启用的手机验证码功能时，才需要传入），长度为4到8位的数字
        /// </summary>
        /// <value>手机验证码（只有启用的手机验证码功能时，才需要传入），长度为4到8位的数字</value>
        [JsonPropertyName("phoneCode")]
        public string PhoneCode { get { return this.PhoneCodeOption; } set { this.PhoneCodeOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignUpRequest {\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  Pwd: ").Append(Pwd).Append("\n");
            sb.Append("  NickName: ").Append(NickName).Append("\n");
            sb.Append("  Avatar: ").Append(Avatar).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  EmailCode: ").Append(EmailCode).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  PhoneCode: ").Append(PhoneCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // UserName (string) maxLength
            if (this.UserName != null && this.UserName.Length > 32)
            {
                yield return new ValidationResult("Invalid value for UserName, length must be less than 32.", new [] { "UserName" });
            }

            // UserName (string) minLength
            if (this.UserName != null && this.UserName.Length < 6)
            {
                yield return new ValidationResult("Invalid value for UserName, length must be greater than 6.", new [] { "UserName" });
            }

            // Pwd (string) maxLength
            if (this.Pwd != null && this.Pwd.Length > 32)
            {
                yield return new ValidationResult("Invalid value for Pwd, length must be less than 32.", new [] { "Pwd" });
            }

            // Pwd (string) minLength
            if (this.Pwd != null && this.Pwd.Length < 6)
            {
                yield return new ValidationResult("Invalid value for Pwd, length must be greater than 6.", new [] { "Pwd" });
            }

            if (this.Pwd != null) {
                // Pwd (string) pattern
                Regex regexPwd = new Regex(@"^[a-zA-Z0-9_\-!@#$%^&*()]*$", RegexOptions.CultureInvariant);

                if (!regexPwd.Match(this.Pwd).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Pwd, must match a pattern of " + regexPwd, new [] { "Pwd" });
                }
            }

            // NickName (string) maxLength
            if (this.NickName != null && this.NickName.Length > 32)
            {
                yield return new ValidationResult("Invalid value for NickName, length must be less than 32.", new [] { "NickName" });
            }

            // NickName (string) minLength
            if (this.NickName != null && this.NickName.Length < 4)
            {
                yield return new ValidationResult("Invalid value for NickName, length must be greater than 4.", new [] { "NickName" });
            }

            // Avatar (string) maxLength
            if (this.Avatar != null && this.Avatar.Length > 999)
            {
                yield return new ValidationResult("Invalid value for Avatar, length must be less than 999.", new [] { "Avatar" });
            }

            // Data (string) maxLength
            if (this.Data != null && this.Data.Length > 9999)
            {
                yield return new ValidationResult("Invalid value for Data, length must be less than 9999.", new [] { "Data" });
            }

            if (this.EmailCodeOption.Value != null) {
                // EmailCode (string) pattern
                Regex regexEmailCode = new Regex(@"\d{4,8}$", RegexOptions.CultureInvariant);

                if (this.EmailCodeOption.Value != null &&!regexEmailCode.Match(this.EmailCodeOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EmailCode, must match a pattern of " + regexEmailCode, new [] { "EmailCode" });
                }
            }

            if (this.PhoneOption.Value != null) {
                // Phone (string) pattern
                Regex regexPhone = new Regex(@"^(\d{11})?$", RegexOptions.CultureInvariant);

                if (this.PhoneOption.Value != null &&!regexPhone.Match(this.PhoneOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Phone, must match a pattern of " + regexPhone, new [] { "Phone" });
                }
            }

            if (this.PhoneCodeOption.Value != null) {
                // PhoneCode (string) pattern
                Regex regexPhoneCode = new Regex(@"\d{4,8}$", RegexOptions.CultureInvariant);

                if (this.PhoneCodeOption.Value != null &&!regexPhoneCode.Match(this.PhoneCodeOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PhoneCode, must match a pattern of " + regexPhoneCode, new [] { "PhoneCode" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SignUpRequest" />
    /// </summary>
    public class SignUpRequestJsonConverter : JsonConverter<SignUpRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="SignUpRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SignUpRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> userName = default;
            Option<string> pwd = default;
            Option<string> nickName = default;
            Option<string> avatar = default;
            Option<string> data = default;
            Option<string> email = default;
            Option<string> emailCode = default;
            Option<string> phone = default;
            Option<string> phoneCode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "userName":
                            userName = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "pwd":
                            pwd = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "nickName":
                            nickName = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "avatar":
                            avatar = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "data":
                            data = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "email":
                            email = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "emailCode":
                            emailCode = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "phone":
                            phone = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "phoneCode":
                            phoneCode = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!userName.IsSet)
                throw new ArgumentException("Property is required for class SignUpRequest.", nameof(userName));

            if (!pwd.IsSet)
                throw new ArgumentException("Property is required for class SignUpRequest.", nameof(pwd));

            if (userName.IsSet && userName.Value == null)
                throw new ArgumentNullException(nameof(userName), "Property is not nullable for class SignUpRequest.");

            if (pwd.IsSet && pwd.Value == null)
                throw new ArgumentNullException(nameof(pwd), "Property is not nullable for class SignUpRequest.");

            return new SignUpRequest(userName.Value, pwd.Value, nickName, avatar, data, email, emailCode, phone, phoneCode);
        }

        /// <summary>
        /// Serializes a <see cref="SignUpRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="signUpRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SignUpRequest signUpRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, signUpRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SignUpRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="signUpRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SignUpRequest signUpRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (signUpRequest.UserName == null)
                throw new ArgumentNullException(nameof(signUpRequest.UserName), "Property is required for class SignUpRequest.");

            if (signUpRequest.Pwd == null)
                throw new ArgumentNullException(nameof(signUpRequest.Pwd), "Property is required for class SignUpRequest.");

            writer.WriteString("userName", signUpRequest.UserName);

            writer.WriteString("pwd", signUpRequest.Pwd);

            if (signUpRequest.NickNameOption.IsSet)
                if (signUpRequest.NickNameOption.Value != null)
                    writer.WriteString("nickName", signUpRequest.NickName);
                else
                    writer.WriteNull("nickName");

            if (signUpRequest.AvatarOption.IsSet)
                if (signUpRequest.AvatarOption.Value != null)
                    writer.WriteString("avatar", signUpRequest.Avatar);
                else
                    writer.WriteNull("avatar");

            if (signUpRequest.DataOption.IsSet)
                if (signUpRequest.DataOption.Value != null)
                    writer.WriteString("data", signUpRequest.Data);
                else
                    writer.WriteNull("data");

            if (signUpRequest.EmailOption.IsSet)
                if (signUpRequest.EmailOption.Value != null)
                    writer.WriteString("email", signUpRequest.Email);
                else
                    writer.WriteNull("email");

            if (signUpRequest.EmailCodeOption.IsSet)
                if (signUpRequest.EmailCodeOption.Value != null)
                    writer.WriteString("emailCode", signUpRequest.EmailCode);
                else
                    writer.WriteNull("emailCode");

            if (signUpRequest.PhoneOption.IsSet)
                if (signUpRequest.PhoneOption.Value != null)
                    writer.WriteString("phone", signUpRequest.Phone);
                else
                    writer.WriteNull("phone");

            if (signUpRequest.PhoneCodeOption.IsSet)
                if (signUpRequest.PhoneCodeOption.Value != null)
                    writer.WriteString("phoneCode", signUpRequest.PhoneCode);
                else
                    writer.WriteNull("phoneCode");
        }
    }
}
