// <auto-generated>
/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using ZSGF.Client.Client;

namespace ZSGF.Client.Model
{
    /// <summary>
    /// UserProfileResult
    /// </summary>
    public partial class UserProfileResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserProfileResult" /> class.
        /// </summary>
        /// <param name="appKey">appKey</param>
        /// <param name="platform">platform</param>
        /// <param name="unionID">unionID</param>
        /// <param name="phone">phone</param>
        /// <param name="createDate">createDate</param>
        /// <param name="userName">userName</param>
        /// <param name="phoneIsValid">phoneIsValid</param>
        /// <param name="data">data</param>
        /// <param name="email">email</param>
        /// <param name="emailIsValid">emailIsValid</param>
        /// <param name="lastUpdate">lastUpdate</param>
        /// <param name="nickName">nickName</param>
        /// <param name="id">id</param>
        /// <param name="avatar">avatar</param>
        /// <param name="currencies">currencies</param>
        /// <param name="role">role</param>
        [JsonConstructor]
        public UserProfileResult(Option<string> appKey = default, Option<string> platform = default, Option<string> unionID = default, Option<string> phone = default, Option<DateTime?> createDate = default, Option<string> userName = default, Option<bool?> phoneIsValid = default, Option<string> data = default, Option<string> email = default, Option<bool?> emailIsValid = default, Option<DateTime?> lastUpdate = default, Option<string> nickName = default, Option<long?> id = default, Option<string> avatar = default, Option<List<UserCurrency>> currencies = default, Option<string> role = default)
        {
            AppKeyOption = appKey;
            PlatformOption = platform;
            UnionIDOption = unionID;
            PhoneOption = phone;
            CreateDateOption = createDate;
            UserNameOption = userName;
            PhoneIsValidOption = phoneIsValid;
            DataOption = data;
            EmailOption = email;
            EmailIsValidOption = emailIsValid;
            LastUpdateOption = lastUpdate;
            NickNameOption = nickName;
            IdOption = id;
            AvatarOption = avatar;
            CurrenciesOption = currencies;
            RoleOption = role;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AppKey
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> AppKeyOption { get; private set; }

        /// <summary>
        /// Gets or Sets AppKey
        /// </summary>
        [JsonPropertyName("appKey")]
        public string AppKey { get { return this.AppKeyOption; } set { this.AppKeyOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Platform
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PlatformOption { get; private set; }

        /// <summary>
        /// Gets or Sets Platform
        /// </summary>
        [JsonPropertyName("platform")]
        public string Platform { get { return this.PlatformOption; } set { this.PlatformOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of UnionID
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> UnionIDOption { get; private set; }

        /// <summary>
        /// Gets or Sets UnionID
        /// </summary>
        [JsonPropertyName("unionID")]
        public string UnionID { get { return this.UnionIDOption; } set { this.UnionIDOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Phone
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PhoneOption { get; private set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [JsonPropertyName("phone")]
        public string Phone { get { return this.PhoneOption; } set { this.PhoneOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of CreateDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreateDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreateDate
        /// </summary>
        [JsonPropertyName("createDate")]
        public DateTime? CreateDate { get { return this.CreateDateOption; } set { this.CreateDateOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Used to track the state of UserName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> UserNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserName
        /// </summary>
        [JsonPropertyName("userName")]
        public string UserName { get { return this.UserNameOption; } set { this.UserNameOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of PhoneIsValid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> PhoneIsValidOption { get; private set; }

        /// <summary>
        /// Gets or Sets PhoneIsValid
        /// </summary>
        [JsonPropertyName("phoneIsValid")]
        public bool? PhoneIsValid { get { return this.PhoneIsValidOption; } set { this.PhoneIsValidOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public string Data { get { return this.DataOption; } set { this.DataOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Email
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> EmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get { return this.EmailOption; } set { this.EmailOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of EmailIsValid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EmailIsValidOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmailIsValid
        /// </summary>
        [JsonPropertyName("emailIsValid")]
        public bool? EmailIsValid { get { return this.EmailIsValidOption; } set { this.EmailIsValidOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of LastUpdate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> LastUpdateOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastUpdate
        /// </summary>
        [JsonPropertyName("lastUpdate")]
        public DateTime? LastUpdate { get { return this.LastUpdateOption; } set { this.LastUpdateOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Used to track the state of NickName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NickNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets NickName
        /// </summary>
        [JsonPropertyName("nickName")]
        public string NickName { get { return this.NickNameOption; } set { this.NickNameOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public long? Id { get { return this.IdOption; } set { this.IdOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of Avatar
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> AvatarOption { get; private set; }

        /// <summary>
        /// Gets or Sets Avatar
        /// </summary>
        [JsonPropertyName("avatar")]
        public string Avatar { get { return this.AvatarOption; } set { this.AvatarOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Currencies
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<UserCurrency>> CurrenciesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Currencies
        /// </summary>
        [JsonPropertyName("currencies")]
        public List<UserCurrency> Currencies { get { return this.CurrenciesOption; } set { this.CurrenciesOption = new Option<List<UserCurrency>>(value); } }

        /// <summary>
        /// Used to track the state of Role
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> RoleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [JsonPropertyName("role")]
        public string Role { get { return this.RoleOption; } set { this.RoleOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserProfileResult {\n");
            sb.Append("  AppKey: ").Append(AppKey).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  UnionID: ").Append(UnionID).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  CreateDate: ").Append(CreateDate).Append("\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  PhoneIsValid: ").Append(PhoneIsValid).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  EmailIsValid: ").Append(EmailIsValid).Append("\n");
            sb.Append("  LastUpdate: ").Append(LastUpdate).Append("\n");
            sb.Append("  NickName: ").Append(NickName).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Avatar: ").Append(Avatar).Append("\n");
            sb.Append("  Currencies: ").Append(Currencies).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UserProfileResult" />
    /// </summary>
    public class UserProfileResultJsonConverter : JsonConverter<UserProfileResult>
    {
        /// <summary>
        /// The format to use to serialize CreateDate
        /// </summary>
        public static string CreateDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize LastUpdate
        /// </summary>
        public static string LastUpdateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="UserProfileResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UserProfileResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> appKey = default;
            Option<string> platform = default;
            Option<string> unionID = default;
            Option<string> phone = default;
            Option<DateTime?> createDate = default;
            Option<string> userName = default;
            Option<bool?> phoneIsValid = default;
            Option<string> data = default;
            Option<string> email = default;
            Option<bool?> emailIsValid = default;
            Option<DateTime?> lastUpdate = default;
            Option<string> nickName = default;
            Option<long?> id = default;
            Option<string> avatar = default;
            Option<List<UserCurrency>> currencies = default;
            Option<string> role = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "appKey":
                            appKey = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "platform":
                            platform = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "unionID":
                            unionID = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "phone":
                            phone = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "createDate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                createDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "userName":
                            userName = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "phoneIsValid":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                phoneIsValid = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "data":
                            data = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "email":
                            email = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "emailIsValid":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                emailIsValid = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "lastUpdate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                lastUpdate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "nickName":
                            nickName = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "avatar":
                            avatar = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "currencies":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                currencies = new Option<List<UserCurrency>>(JsonSerializer.Deserialize<List<UserCurrency>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "role":
                            role = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (createDate.IsSet && createDate.Value == null)
                throw new ArgumentNullException(nameof(createDate), "Property is not nullable for class UserProfileResult.");

            if (phoneIsValid.IsSet && phoneIsValid.Value == null)
                throw new ArgumentNullException(nameof(phoneIsValid), "Property is not nullable for class UserProfileResult.");

            if (emailIsValid.IsSet && emailIsValid.Value == null)
                throw new ArgumentNullException(nameof(emailIsValid), "Property is not nullable for class UserProfileResult.");

            if (lastUpdate.IsSet && lastUpdate.Value == null)
                throw new ArgumentNullException(nameof(lastUpdate), "Property is not nullable for class UserProfileResult.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class UserProfileResult.");

            return new UserProfileResult(appKey, platform, unionID, phone, createDate, userName, phoneIsValid, data, email, emailIsValid, lastUpdate, nickName, id, avatar, currencies, role);
        }

        /// <summary>
        /// Serializes a <see cref="UserProfileResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userProfileResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UserProfileResult userProfileResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, userProfileResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UserProfileResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userProfileResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UserProfileResult userProfileResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (userProfileResult.AppKeyOption.IsSet)
                if (userProfileResult.AppKeyOption.Value != null)
                    writer.WriteString("appKey", userProfileResult.AppKey);
                else
                    writer.WriteNull("appKey");

            if (userProfileResult.PlatformOption.IsSet)
                if (userProfileResult.PlatformOption.Value != null)
                    writer.WriteString("platform", userProfileResult.Platform);
                else
                    writer.WriteNull("platform");

            if (userProfileResult.UnionIDOption.IsSet)
                if (userProfileResult.UnionIDOption.Value != null)
                    writer.WriteString("unionID", userProfileResult.UnionID);
                else
                    writer.WriteNull("unionID");

            if (userProfileResult.PhoneOption.IsSet)
                if (userProfileResult.PhoneOption.Value != null)
                    writer.WriteString("phone", userProfileResult.Phone);
                else
                    writer.WriteNull("phone");

            if (userProfileResult.CreateDateOption.IsSet)
                writer.WriteString("createDate", userProfileResult.CreateDateOption.Value.Value.ToString(CreateDateFormat));

            if (userProfileResult.UserNameOption.IsSet)
                if (userProfileResult.UserNameOption.Value != null)
                    writer.WriteString("userName", userProfileResult.UserName);
                else
                    writer.WriteNull("userName");

            if (userProfileResult.PhoneIsValidOption.IsSet)
                writer.WriteBoolean("phoneIsValid", userProfileResult.PhoneIsValidOption.Value.Value);

            if (userProfileResult.DataOption.IsSet)
                if (userProfileResult.DataOption.Value != null)
                    writer.WriteString("data", userProfileResult.Data);
                else
                    writer.WriteNull("data");

            if (userProfileResult.EmailOption.IsSet)
                if (userProfileResult.EmailOption.Value != null)
                    writer.WriteString("email", userProfileResult.Email);
                else
                    writer.WriteNull("email");

            if (userProfileResult.EmailIsValidOption.IsSet)
                writer.WriteBoolean("emailIsValid", userProfileResult.EmailIsValidOption.Value.Value);

            if (userProfileResult.LastUpdateOption.IsSet)
                writer.WriteString("lastUpdate", userProfileResult.LastUpdateOption.Value.Value.ToString(LastUpdateFormat));

            if (userProfileResult.NickNameOption.IsSet)
                if (userProfileResult.NickNameOption.Value != null)
                    writer.WriteString("nickName", userProfileResult.NickName);
                else
                    writer.WriteNull("nickName");

            if (userProfileResult.IdOption.IsSet)
                writer.WriteNumber("id", userProfileResult.IdOption.Value.Value);

            if (userProfileResult.AvatarOption.IsSet)
                if (userProfileResult.AvatarOption.Value != null)
                    writer.WriteString("avatar", userProfileResult.Avatar);
                else
                    writer.WriteNull("avatar");

            if (userProfileResult.CurrenciesOption.IsSet)
                if (userProfileResult.CurrenciesOption.Value != null)
                {
                    writer.WritePropertyName("currencies");
                    JsonSerializer.Serialize(writer, userProfileResult.Currencies, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("currencies");
            if (userProfileResult.RoleOption.IsSet)
                if (userProfileResult.RoleOption.Value != null)
                    writer.WriteString("role", userProfileResult.Role);
                else
                    writer.WriteNull("role");
        }
    }
}
